var age = 25;
age = true;
console.log(age);
age = 'Talha';
console.log(age);
var mixed = [];
mixed.push('Talha');
mixed.push(24);
console.log(mixed);
var ninja;
ninja = { name: 'Khan', age: 23 };
console.log(ninja);
ninja = { name: 23, age: 'Ta' };
console.log(ninja);
